import Link from "next/link";

export const metadata = {
  title: "Terms of Service – RetroGrade",
  description: "Terms of Service for the RetroGrade platform.",
};

export default function TermsOfService() {
  return (
    <main className="min-h-screen bg-white">
      {/* Header */}
      <header className="border-b border-slate-100">
        <div className="max-w-4xl mx-auto px-6 py-6 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2.5">
            <div className="w-8 h-8 rounded-lg bg-emerald-600 flex items-center justify-center font-bold text-white text-sm">R</div>
            <span className="font-semibold text-lg tracking-tight text-slate-800">Retro<span className="text-emerald-600">Grade</span></span>
          </Link>
          <Link href="/" className="text-sm text-slate-400 hover:text-emerald-600 transition-colors">&larr; Back to Home</Link>
        </div>
      </header>

      {/* Content */}
      <div className="max-w-4xl mx-auto px-6 py-16">
        <h1 className="text-3xl font-bold tracking-tight text-slate-900 mb-2">Terms of Service</h1>
        <p className="text-sm text-slate-400 mb-12">Last updated: February 27, 2026</p>

        <div className="space-y-10 text-slate-600 text-sm leading-relaxed">
          <section>
            <h2 className="text-lg font-semibold text-slate-800 mb-3">1. Acceptance of Terms</h2>
            <p>By accessing or using RetroGrade (&quot;the Service&quot;), operated by RetroGrade (&quot;we&quot;, &quot;us&quot;, or &quot;our&quot;), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the Service.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-800 mb-3">2. Description of Service</h2>
            <p>RetroGrade provides data-driven competitive intelligence for restaurants, including competitor analysis based on historic data, review sentiment analysis, and performance benchmarking. The Service uses publicly available data from platforms such as Google Maps to generate reports and insights.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-800 mb-3">3. User Accounts</h2>
            <ul className="list-disc pl-5 space-y-2">
              <li>You may sign in using Google authentication through our secure login system.</li>
              <li>You are responsible for maintaining the confidentiality of your account credentials.</li>
              <li>You agree to provide accurate and complete information when creating your account.</li>
              <li>You must notify us immediately of any unauthorized use of your account.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-800 mb-3">4. Acceptable Use</h2>
            <p>You agree not to:</p>
            <ul className="list-disc pl-5 space-y-2 mt-2">
              <li>Use the Service for any unlawful purpose or in violation of any applicable laws.</li>
              <li>Attempt to reverse-engineer, decompile, or disassemble any part of the Service.</li>
              <li>Scrape, crawl, or use automated tools to extract data from the Service beyond normal usage.</li>
              <li>Interfere with the security or proper functioning of the Service.</li>
              <li>Resell, redistribute, or sublicense access to reports or data generated by the Service without prior written consent.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-800 mb-3">5. Subscriptions and Payments</h2>
            <ul className="list-disc pl-5 space-y-2">
              <li>Certain features of the Service may require a paid subscription.</li>
              <li>Subscription fees are billed in advance on a recurring basis (monthly or annually) depending on your selected plan.</li>
              <li>All payments are processed securely through our third-party payment provider (Stripe).</li>
              <li>Refunds are handled on a case-by-case basis. Please contact us for refund requests.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-800 mb-3">6. Intellectual Property</h2>
            <p>All content, features, and functionality of the Service — including but not limited to text, graphics, logos, and software — are owned by RetroGrade and protected by copyright, trademark, and other intellectual property laws. Reports generated for you are licensed for your personal or internal business use only.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-800 mb-3">7. Data and Reports</h2>
            <ul className="list-disc pl-5 space-y-2">
              <li>Reports are generated using publicly available data and AI-powered analysis.</li>
              <li>While we strive for accuracy, we do not guarantee that all data or insights will be error-free or complete.</li>
              <li>Reports and insights are provided for informational purposes and should not be the sole basis for business decisions.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-800 mb-3">8. Limitation of Liability</h2>
            <p>To the maximum extent permitted by law, RetroGrade shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including but not limited to loss of profits, data, or business opportunities, arising out of or related to your use of the Service.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-800 mb-3">9. Disclaimer of Warranties</h2>
            <p>The Service is provided on an &quot;as is&quot; and &quot;as available&quot; basis without warranties of any kind, either express or implied. We do not warrant that the Service will be uninterrupted, secure, or error-free.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-800 mb-3">10. Termination</h2>
            <p>We reserve the right to suspend or terminate your access to the Service at any time, with or without cause, and with or without notice. Upon termination, your right to use the Service will immediately cease.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-800 mb-3">11. Changes to Terms</h2>
            <p>We may update these Terms of Service from time to time. We will notify you of any material changes by posting the updated terms on the Service. Your continued use of the Service after changes are posted constitutes your acceptance of the revised terms.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-800 mb-3">12. Governing Law</h2>
            <p>These Terms shall be governed by and construed in accordance with the laws of India, without regard to its conflict of law provisions.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-800 mb-3">13. Contact Us</h2>
            <p>If you have any questions about these Terms of Service, please contact us at:</p>
            <div className="mt-3 p-4 bg-slate-50 rounded-xl border border-slate-100">
              <p className="font-semibold text-slate-700">RetroGrade</p>
              <p>Email: <a href="mailto:support@retrograde.app" className="text-emerald-600 hover:underline">support@retrograde.app</a></p>
              <p>Visit our <Link href="/contact" className="text-emerald-600 hover:underline">Contact Page</Link></p>
            </div>
          </section>
        </div>
      </div>

      {/* Footer */}
      <footer className="border-t border-slate-100">
        <div className="max-w-4xl mx-auto px-6 py-8 flex flex-col md:flex-row items-center justify-between gap-4">
          <p className="text-xs text-slate-400">&copy; 2026 RetroGrade. All rights reserved.</p>
          <div className="flex gap-6">
            <Link href="/privacy" className="text-xs text-slate-400 hover:text-emerald-600 transition-colors">Privacy Policy</Link>
            <Link href="/terms" className="text-xs text-slate-400 hover:text-emerald-600 transition-colors font-semibold">Terms of Service</Link>
            <Link href="/contact" className="text-xs text-slate-400 hover:text-emerald-600 transition-colors">Contact Us</Link>
          </div>
        </div>
      </footer>
    </main>
  );
}
